# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "K9IRJ0/AMbOScOvwzVtIfahSLIPp4U9dwkTOlIW0N14T1phfVKLfMWrWptD9EAuYTkqrmKfJw2F8eO/+9KHn1ngG9f/leZ8hFrkZtPylbf5VKcC9yLn8iQDRSzJ6GZPClIwA7Oh5urzoiFEW9K/xqWiv18GAQXeM5BgcqXpJaBFHpYwsXj4J5p+0A7Mk7VppBo5vm5Z/cP6CUQQeV9difMOBIM4kZyrAHzpuVK3anox9iR6H4YoNWWBvYOcRg7D5hCHTsnWkkO33Wbn8DcQ5VdHeTZDvlFuSaeK6lpy/ZW/CuHfQTX4II3ZFxfT+6frh09n/OUmkLve5Mjpr5RTNS9TmpkIyLWgFlKHgP6i5s+wVTtkFRL9mTnaZUpETLY3EoKgpFy45DetOoYSGvYvxP9BpA4DP3Oo+mTLg5Rqmjlsz6LdkKU+DMM8RSVN/PjAynfIIXJcKdyAodbQYdqk+hcKSiVgF3sN3/oXOEPJKrGXH4E6pRK2GhmEZN0kaEo219ywGY8CwI0+x94/90S1KBZKRVz+bZeL9dGlNvSq+co79WaUa1EkhBrc6vslk5e5n824pbmM+V1C7s4N3lPiZC+LcBmmqD/9FGDdInvz9AkaoGI2m3Pyjtwsgu6VLyjatiovol4eOHQHEd2wL9gYIMicgHmT/Oc8MQbAxFUw+h+g="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
