travis:
  secure:
    BINSTAR_TOKEN: K9IRJ0/AMbOScOvwzVtIfahSLIPp4U9dwkTOlIW0N14T1phfVKLfMWrWptD9EAuYTkqrmKfJw2F8eO/+9KHn1ngG9f/leZ8hFrkZtPylbf5VKcC9yLn8iQDRSzJ6GZPClIwA7Oh5urzoiFEW9K/xqWiv18GAQXeM5BgcqXpJaBFHpYwsXj4J5p+0A7Mk7VppBo5vm5Z/cP6CUQQeV9difMOBIM4kZyrAHzpuVK3anox9iR6H4YoNWWBvYOcRg7D5hCHTsnWkkO33Wbn8DcQ5VdHeTZDvlFuSaeK6lpy/ZW/CuHfQTX4II3ZFxfT+6frh09n/OUmkLve5Mjpr5RTNS9TmpkIyLWgFlKHgP6i5s+wVTtkFRL9mTnaZUpETLY3EoKgpFy45DetOoYSGvYvxP9BpA4DP3Oo+mTLg5Rqmjlsz6LdkKU+DMM8RSVN/PjAynfIIXJcKdyAodbQYdqk+hcKSiVgF3sN3/oXOEPJKrGXH4E6pRK2GhmEZN0kaEo219ywGY8CwI0+x94/90S1KBZKRVz+bZeL9dGlNvSq+co79WaUa1EkhBrc6vslk5e5n824pbmM+V1C7s4N3lPiZC+LcBmmqD/9FGDdInvz9AkaoGI2m3Pyjtwsgu6VLyjatiovol4eOHQHEd2wL9gYIMicgHmT/Oc8MQbAxFUw+h+g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
