travis:
  secure:
    BINSTAR_TOKEN: P/3HSxVcK4x1b5glUJAGdbVD1xZix+kLSysDeBH01qWYXoZfdPT1aOuvU1LbZcO1AkUP4DIQoCfZ+Aipikdm9uI7qK8Urswpd975foX5TI7/syESDCzorayqgDRtaoMzquveRNgcXgMnard1VZrSW40s6G+xB7xan9npTK219ZFmvS0llO4Blqem1EhVLLCtoOj0pKfRsfGPfTujoAFJTU+PXv58XRufusmDMQylp50nP3cqROp5Wz9e+JoNTK3J7HA+CooxmUOCTRBU7QQD2Qo1Ve9crQg2p+e2FZbFLm+6HCBt30hFDE1re8sG+bIVjViUc0Nq8hBewFPQkIMgevJJToOvSLnn6VypuAEKHnSs6lJT5ikbvnacaKp6+tQ7FC3UU01dWDzMaVKmZq9JWtFTDiaBVbqlEYxpF4PbTFLEEtfwQ69Q6+hssw2xBDZh2DIeyhJ7Jt/JwXb6NNJnHN9oU6Mx4xrd/roycYPtu2LYvGRJzFBluKcBYwBOceXp0xz4gFDcjUBy7lnqJ3JTeUl+egMvcAO7Um9KjModWKTzeVBvz8IJ+pH+XgRZFAqPB2qj0yvYzaqj2FssNNmMZY+tC2EL+KD3DLueMVzD+bZtwIMfmGfGKk0HR060pORRAF+/PFLR02BUfT8emD0eHuJaVX5vHF0/wNUUO5kYtUw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
